#!/usr/bin/env bash

# Script to poll the current CPU temperature.
# This script runs until it's manually terminated.

# Requires: gawk
# Usage: cpu-temp

while true; do
  echo $(awk '{printf("%.2f\n", ($1/1000))}' /sys/class/hwmon/hwmon4/temp1_input)
  sleep 5
done
