#!/usr/bin/env bash

# Script to poll the current memory usage.
# This script runs until it's manually terminated.

# Requires: gawk, coreutils
# Usage: memory-usage

while true; do
  echo $(free | grep Mem | awk '{printf("%.2f\n", ($3/$2 * 100.0))}')
  sleep 5
done
